apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citus
      role: coordinator
  template:
    metadata:
      labels:
        app: citus
        role: coordinator
    spec:
      containers:
        - name: coordinator
          image: citusdata/citus:11.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: historia_clinica
