apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-citus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
        - name: middleware
          image: python:3.9
          command: ["sh", "-c", "pip install psycopg2-binary flask && python /app/middleware_citus.py"]
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: "citus-coordinator"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "historia_clinica"
          volumeMounts:
            - name: middleware-code
              mountPath: /app
      restartPolicy: Always
      volumes:
        - name: middleware-code
          configMap:
            name: middleware-citus
