apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citus-worker
      role: worker1
  template:
    metadata:
      labels:
        app: citus-worker
        role: worker1
    spec:
      containers:
        - name: worker1
          image: citusdata/citus:12.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "historia_clinica"
            - name: PGUSER
              value: "admin"
            - name: PGPASSWORD
              value: "admin"
            - name: PGDATABASE
              value: "historia_clinica"
---
apiVersion: v1
kind: Service
metadata:
  name: citus-worker-1
spec:
  selector:
    app: citus-worker
    role: worker1
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
